#!/usr/bin/python3
import cgitb
import cgi
import zlib
import sh
import os

cgitb.enable()
print("Content-type: text/plain\n\n")
params = cgi.parse()

name = params.get('name')
key = params.get('key')
ipi = params.get('ip')

if ipi:
    ip = ipi[0]
else:
    ip = os.environ.get("REMOTE_ADDR", "")

if name and key:
    name_upper = name[0].upper().encode('utf-8')  # Encode to bytes for zlib.adler32
    if str(zlib.adler32(name_upper, 1234)) == key[0]:
        with open("/tmp/nsupdate", 'w') as f:
            f.write("server mydomain.com\n")
            f.write("zone mydomain.com\n")
            f.write(f"update delete {name[0]}.mydomain.com. A\n")
            f.write(f"update add {name[0]}.mydomain.com. 3600 A {ip}\n")
            f.write("show\n")
            f.write("send\n")

        run = sh.nsupdate(
            "-k", "/etc/dyndns/Kdynamic.mydomain.com.+157+06067.key",
            "-v", "/tmp/nsupdate"
        )
        if run.exit_code == 0:
            print(f"Updated {name[0]}.mydomain.com to {ip}")
        else:
            print("nsupdate failed")
    else:
        print("Invalid key")
